%% Settings

clearErthang = 1; % clears all stuff

if clearErthang
    clear all;
end

%% Setup

syms rBO_x(t) rBO_y(t) rBO_z(t) ... % some position vectors
    rCB_x(t) rCB_y(t) rCB_z(t) ...
    rPB_x(t) rPB_y(t) rPB_z(t) ...
    vWO_x(t) vWO_y(t) vWO_z(t) ... %except this one, its a velocity
    rGO_x(t) rGO_y(t) rGO_z(t) ...
    ...
    ... % for the rotation matrices
    phi(t) theta(t) psi(t) ...
    ...
    ... % for moment of inertia
    Ixx(t) Ixy(t) Ixz(t) Iyy(t) Iyz(t) Izz(t) ...
    ...
    ... % lift,moment,and gravity force leftover vars, to make sure math works
    L_x(t) L_y(t) ...
    D_y(t) D_z(t) ...
    Y_x(t) Y_z(t) ...
    l_y(t) l_z(t) ...
    m_x(t) m_z(t) ...
    n_x(t) n_y(t) ...
    Fg_x(t) Fg_y(t) ...
    ...
    ... % some general constants
    k_tether(t) lo_tether(t) mT(t) g(t) rho(t)...
    Sref(t) Bref(t) Cref(t) ...
    ...
    ... % lift and moment coefficients
    cLa(t) cLb(t) cLde(t) cLp(t) cLq(t) cLr(t) ...
    cDtot(t) ...
    cYa(t) cYb(t) cYde(t) cYp(t) cYq(t) cYr(t) ...
    cla(t) clb(t) clde(t) clp(t) clq(t) clr(t) ...
    cma(t) cmb(t) cmde(t) cmp(t) cmq(t) cmr(t) ...
    cna(t) cnb(t) cnde(t) cnp(t) cnq(t) cnr(t) ...
    ...
    ... % de
    de ...
    ;

rBO_B = [rBO_x(t) rBO_y(t) rBO_z(t)];
rCB_B = [rCB_x(t) rCB_y(t) rCB_z(t)];
rPB_B = [rPB_x(t) rPB_y(t) rPB_z(t)];
O_v_WO_O = [vWO_x(t) vWO_y(t) vWO_z(t)];
rGO_O = [rGO_x(t) rGO_y(t) rGO_z(t)];

% C = [C_x C_y C_z];
% D = [D_x D_y D_z];
% Y = [Y_x Y_y Y_z];
% l = [l_x l_y l_z ];
% m = [m_x m_y m_z];
% n = [n_x n_y n_z];

I_B = [
    Ixx(t) Ixy(t) Ixz(t)
    Ixy(t) Iyy(t) Iyz(t)
    Ixz(t) Iyz(t) Izz(t)
    ];


%% DERIVE THE ROTATION MATRIX (Y-Z-X, THETA-PSI-PHI ROTATION SEQUENCE)
Rx_phi = [
    1   0               0
    0   cos(phi(t))     sin(phi(t))
    0   -sin(phi(t))    cos(phi(t))
    ];

Rz_psi = [
    cos(psi(t))     sin(phi(t))    0
    -sin(psi(t))    cos(psi(t))    0
    0               0               1
    ];

Ry_theta = [
    cos(theta(t))   0   -sin(theta(t))
    0               1   0
    sin(theta(t))   0   cos(theta(t))
    ];

% *********************** BcO and OcB *************************************
BcO = (Rx_phi * Rz_psi * Ry_theta);
OcB = transpose(BcO);
% *************************************************************************

%% DERIVE THE TERMS FOR O_omega_B_B AND O_alpha_B

OcB_dot = (diff(OcB));

omega_x_B = [0 0 1]*BcO*OcB_dot*[0;1;0];
omega_y_B = [1 0 0]*BcO*OcB_dot*[0;0;1];
omega_z_B = [0 1 0]*BcO*OcB_dot*[1;0;0];

% ***************** O_omega_B_B and O_alpha_B *****************************
O_omega_B_B = [omega_x_B omega_y_B omega_z_B];
O_alpha_B = (diff(O_omega_B_B));
% *************************************************************************

%% DERIVE EXPRESSION FOR O_v_BO_B

% 1st transport theorem
% *************************** O_v_BO_B ************************************
O_v_BO_B = ( ...
    diff(rBO_B) + ...
    cross(O_omega_B_B ,rBO_B) ... 
    );
% *************************************************************************

%% DERIVE EXPRESSION FOR O_a_BO_B

% 2nd transport theorem
% *************************** O_a_BO_B ************************************
O_a_BO_B = ( ...
    diff(diff(rBO_B)) + ...
    (2 * cross(O_omega_B_B , diff(rBO_B))) + ...
    cross(O_alpha_B , rBO_B) + ...
    cross(O_omega_B_B , cross(O_omega_B_B , rBO_B)) ...
    );
% *************************************************************************

%% DERIVE EXPRESSION FOR O_O_h_B_B and its O_derivative

% *************************** O_O_h_B_B ***********************************
O_O_h_B_B = transpose((I_B * transpose(O_omega_B_B)));
% *************************************************************************

% 1st transport theorem
% *********************** Oddt_O_O_h_B_B **********************************
Oddt_O_O_h_B_B = ( ...
    diff(O_O_h_B_B) + ...
    cross(O_omega_B_B , O_O_h_B_B) ...
    );
% *************************************************************************


%% DERIVE EXPRESSIONS FOR alpha AND beta AND vel (AERO)

O_v_WO_B = transpose((BcO * transpose(O_v_WO_O)));
O_v_OB_B = -O_v_BO_B;

% ************************* O_v_WB_B **************************************
O_v_WB_B = (O_v_WO_B + O_v_OB_B);
% *************************************************************************

jB_proj_O_v_WB_B = O_v_WB_B - (O_v_WB_B * [0; 1; 0]);
kB_proj_O_v_WB_B = O_v_WB_B - (O_v_WB_B * [0; 0; 1]);

% *********************** alpha AND beta AND windspeed ********************
alpha = ( ...
    acos( ...
    (jB_proj_O_v_WB_B * [1; 0; 0]) ...
    ) ...
    );

beta = ( ...
    acos( ...
    (kB_proj_O_v_WB_B * [1; 0; 0]) ...
    ) ...
    );

windspeed = (norm(O_v_WB_B));
% *************************************************************************

%% DERIVE EXPRESSIONS FOR AERO FORCE/MOMENT COEFFICIENTS

CL = ( ...
    (cLa(t)* alpha) + (cLb(t) * beta) + (cLde(t) * de) + (cLp(t) * O_omega_B_B(1)) ...
    + (cLq(t) * O_omega_B_B(2)) + (cLr(t) * O_omega_B_B(3)) ...
    );

CD = cDtot(t);

CY = ( ...
    (cYa(t) * alpha) + (cYb(t) * beta) + (cYde(t) * de) + (cYp(t) * O_omega_B_B(1)) ...
    + (cYq(t) * O_omega_B_B(2)) + (cYr(t) * O_omega_B_B(3)) ...
    );

Cl = ( ...
    (cla(t)* alpha) + (clb(t) * beta) + (clde(t) * de) + (clp(t) * O_omega_B_B(1)) ...
    + (clq(t) * O_omega_B_B(2)) + (clr(t) * O_omega_B_B(3)) ...
    );

Cm = ( ...
    (cma(t) * alpha) + (cmb(t) * beta) + (cmde(t) * de) + (cmp(t) * O_omega_B_B(1)) ...
    + (cmq(t) * O_omega_B_B(2)) + (cmr(t) * O_omega_B_B(3)) ...
    );

Cn = ( ...
    (cna(t) * alpha) + (cnb(t) * beta) + (cnde(t) * de) + (cnp(t) * O_omega_B_B(1)) ...
    + (cnq(t) * O_omega_B_B(2)) + (cnr(t) * O_omega_B_B(3)) ...
    );

%% DERIVE EXPRESSION FOR Q

Q = (0.5 * rho * windspeed * windspeed);

%% DERIVE EXPRESSIONS FOR AERO FORCES AND MOMENTS

L_z = (CL * Q * Sref);

D_x = (CD * Q * Sref);

Y_y = (CY * Q * Sref);
 
l_x = (Cl * Q * Sref * Bref);

m_y = (Cm * Q * Sref * Cref);

n_z = (Cn * Q * Sref * Bref);

% assign them to their vectors
L = [L_x(t) L_y(t) L_z(t)];

D = [D_x(t) D_y(t) D_z(t)];

Y = [Y_x(t) Y_y(t) Y_z(t)];

l = [l_x(t) l_y(t) l_z(t)];

m = [m_x(t) m_y(t) m_z(t)];

n = [n_x(t) n_y(t) n_z(t)];

% Now for the last few torques
tau_L = (cross(L , rCB_B));

tau_D = (cross(D , rCB_B));

tau_Y = (cross(Y , rCB_B));

%% DERIVE FORCE AND MOMENT VECTOR FOR TETHER

rGO_B = transpose((BcO*transpose(rGO_O)));
rGP_B = (rGO_B - rBO_B - rPB_B);

lcurrent_tether = norm(rGP_B);
dl_tether = lcurrent_tether - lo_tether;
sigmoidFnc = exp(1000000*dl_tether) / (1 + exp(1000000*dl_tether));

normT = (sigmoidFnc(t) * (k_tether(t) * dl_tether(t)));

T = (normT * (rGP_B / norm(rGP_B)));

tau_T = (cross(T , rPB_B));

%% DERIVE GRAVITY VECTOR

Fg_z = mT * g;

Fg_O = [Fg_x(t) Fg_y(t) Fg_z(t)];

Fg_B = transpose((BcO * transpose(Fg_O)));

%% DERIVE EXPRESSIONS FOR F = MA AND ODDT(H) = TAU

F_over_M = ((Fg_B + T + L + D + Y) / mT(t));

tauTot = (l + m + n + tau_L + tau_D + tau_Y + tau_T);

linEQ = O_a_BO_B == F_over_M;
angEQ = Oddt_O_O_h_B_B == tauTot;

EQ_unsolved = [linEQ , angEQ];

symvar(EQ_unsolved)

%% SUBSTITUTE STUFF INTO OTHER STUFF

syms rBO_X rBO_Y rBO_Z ... 
    rBO_X_d rBO_Y_d rBO_Z_d ...
    rBO_X_d_d rBO_Y_d_d rBO_Z_d_d ...
    ...   
    ...
    rCB_X...
    ...
    ...
    vWO_X vWO_Y vWO_Z ...
    ...
    ...
    ... % for the rotation matrices
    ph th ps ...
    ph_d th_d ps_d ...
    ph_d_d th_d_d ps_d_d ...
    ...
    ...
    CLa CLb CLde CLp CLq CLr ...
    CDtot ...
    CYa CYb CYde CYp CYq CYr ...
    Cla Clb Clde Clp Clq Clr ...
    Cma Cmb Cmde Cmp Cmq Cmr ...
    Cna Cnb Cnde Cnp Cnq Cnr ...
    ;

regVect = [ ...
    str2sym('rBO_x(t)') str2sym('rBO_y(t)') str2sym('rBO_z(t)') ...
    str2sym('diff(rBO_x(t), t)') str2sym('diff(rBO_y(t), t)') str2sym('diff(rBO_z(t), t)') ...
    str2sym('diff(rBO_x(t), t, t)') str2sym('diff(rBO_y(t), t, t)') str2sym('diff(rBO_z(t), t, t)') ...
    ...
    str2sym('rCB_x(t)') str2sym('rCB_y(t)') str2sym('rCB_z(t)') ...
    str2sym('diff(rCB_x(t), t)') str2sym('diff(rCB_y(t), t)') str2sym('diff(rCB_z(t), t)') ...
    str2sym('diff(rCB_x(t), t, t)') str2sym('diff(rCB_y(t), t, t)') str2sym('diff(rCB_z(t), t, t)') ...
    ...   
    str2sym('rPB_x(t)') str2sym('rPB_y(t)') str2sym('rPB_z(t)') ...
    str2sym('diff(rPB_x(t), t)') str2sym('diff(rPB_y(t), t)') str2sym('diff(rPB_z(t), t)') ...
    str2sym('diff(rPB_x(t), t, t)') str2sym('diff(rPB_y(t), t, t)') str2sym('diff(rPB_z(t), t, t)') ...
    ...
    str2sym('vWO_x(t)') str2sym('vWO_y(t)') str2sym('vWO_z(t)') ... %except this one, its a velocity
    str2sym('diff(vWO_x(t), t)') str2sym('diff(vWO_y(t), t)') str2sym('diff(vWO_z(t), t)') ...
    str2sym('diff(vWO_x(t), t, t)') str2sym('diff(vWO_y(t), t, t)') str2sym('diff(vWO_z(t), t, t)') ...
    ...
    str2sym('rGO_x(t)') str2sym('rGO_y(t)') str2sym('rGO_z(t)') ...
    str2sym('diff(rPB_x(t), t)') str2sym('diff(rPB_y(t), t)') str2sym('diff(rPB_z(t), t)') ...
    str2sym('diff(rPB_x(t), t, t)') str2sym('diff(rPB_y(t), t, t)') str2sym('diff(rPB_z(t), t, t)') ...
    ...
    ...
    ... % for the rotation matrices
    str2sym('phi(t)') str2sym('theta(t)') str2sym('psi(t)') ...
    str2sym('diff(phi(t), t)') str2sym('diff(theta(t), t)') str2sym('diff(psi(t), t)') ...
    str2sym('diff(phi(t), t, t)') str2sym('diff(theta(t), t, t)') str2sym('diff(psi(t), t, t)') ...
    ...
    ...
    ... % for moment of inertia
    str2sym('Ixx(t)') str2sym('Ixy(t)') str2sym('Ixz(t)') str2sym('Iyy(t)') str2sym('Iyz(t)') str2sym('Izz(t)') ...
    str2sym('diff(Ixx(t), t)') str2sym('diff(Ixy(t), t)') str2sym('diff(Ixz(t), t)') ...
    str2sym('diff(Ixx(t), t, t)') str2sym('diff(Ixy(t), t, t)') str2sym('diff(Ixz(t), t, t)') ...
    ...
    str2sym('diff(Iyy(t), t)') str2sym('diff(Iyz(t), t)') str2sym('diff(Izz(t), t)') ...
    str2sym('diff(Iyy(t), t, t)') str2sym('diff(Iyz(t), t, t)') str2sym('diff(Izz(t), t, t)') ...
    ...
    ...
    ... % lift,moment,and gravity force leftover vars, to make sure math works
    str2sym('L_x(t)') str2sym('L_y(t)') ...
    str2sym('D_y(t)') str2sym('D_z(t)') ...
    str2sym('Y_x(t)') str2sym('Y_z(t)') ...
    str2sym('l_y(t)') str2sym('l_z(t)') ...
    str2sym('m_x(t)') str2sym('m_z(t)') ...
    str2sym('n_x(t)') str2sym('n_y(t)') ...
    str2sym('Fg_x(t)') str2sym('Fg_y(t)') ...
    ...
    ... % some general constants
    str2sym('k_tether(t)') str2sym('lo_tether(t)') str2sym('mT(t)') str2sym('g(t)') str2sym('rho(t)') ...
    str2sym('Sref(t)') str2sym('Bref(t)') str2sym('Cref(t)') ...
    ...
    ... % lift and moment coefficients
    str2sym('cLa(t)') str2sym('cLb(t)') str2sym('cLde(t)') str2sym('cLp(t)') str2sym('cLq(t)') str2sym('cLr(t)') ...
    str2sym('cDtot(t)') ...
    str2sym('cYa(t)') str2sym('cYb(t)') str2sym('cYde(t)') str2sym('cYp(t)') str2sym('cYq(t)') str2sym('cYr(t)') ...
    str2sym('cla(t)') str2sym('clb(t)') str2sym('clde(t)') str2sym('clp(t)') str2sym('clq(t)') str2sym('clr(t)') ...
    str2sym('cma(t)') str2sym('cmb(t)') str2sym('cmde(t)') str2sym('cmp(t)') str2sym('cmq(t)') str2sym('cmr(t)') ...
    str2sym('cna(t)') str2sym('cnb(t)') str2sym('cnde(t)') str2sym('cnp(t)') str2sym('cnq(t)') str2sym('cnr(t)') ...
    ...
    ... % de
    de ...
    ];

subVect = [ ...
    rBO_X rBO_Y rBO_Z ...
    rBO_X_d rBO_Y_d rBO_Z_d ...
    rBO_X_d_d rBO_Y_d_d rBO_Z_d_d ...
    ...
    rCB_X -.4751 0 ...
    0 0 0 ...
    0 0 0 ...
    ...   
    0 0.2107 0 ...
    0 0 0 ...
    0 0 0 ...
    ...
    vWO_X vWO_Y vWO_Z ... %except this one, its a velocity
    0 0 0 ...
    0 0 0 ...
    ...
    0 0 152.4 ...
    0 0 0 ...
    0 0 0 ...
    ...
    ...
    ... % for the rotation matrices
    ph th ps ...
    ph_d th_d ps_d ...
    ph_d_d th_d_d ps_d_d ...
    ...
    ...
    ... % for moment of inertia
    0.2119 0.0281 0 0.1473 0 0.0904 ...
    0 0 0 ...
    0 0 0 ...
    ...
    0 0 0 ...
    0 0 0 ...
    ...
    ...
    ... % lift,moment,and gravity force leftover vars, to make sure math works
    0 0 ...
    0 0 ...
    0 0 ...
    0 0 ...
    0 0 ...
    0 0 ...
    0 0 ...
    ...
    ... % some general constants
    37.5 75.914856 1.0862 9.81 1.225...
    0.4 1.4 0.3 ...
    ...
    ... % lift and moment coefficients
    CLa CLb CLde CLp CLq CLr ...
    CDtot ...
    CYa CYb CYde CYp CYq CYr ...
    Cla Clb Clde Clp Clq Clr ...
    Cma Cmb Cmde Cmp Cmq Cmr ...
    Cna Cnb Cnde Cnp Cnq Cnr ...
    ...
    ... % de
    de ...
    ];

    EQ_unsolved_subbed_1 = subs(EQ_unsolved,regVect,subVect);
    %%
    alpha_subbed_1 = subs(alpha,regVect,subVect);
    beta_subbed_1 = subs(beta,regVect,subVect);
    PQR_subbed_1 = subs(O_omega_B_B,regVect,subVect);
    windspeed_subbed_1 = subs(windspeed,regVect,subVect);

%% now solve for state derivatives and extra stuff 

EQ_solved_unsimple_1 = solve(EQ_unsolved_subbed_1,[rBO_X_d_d,rBO_Y_d_d,rBO_Z_d_d,ph_d_d,th_d_d,ps_d_d]);

EQ_solve_simple_1(1) = simplify(EQ_solved_unsimple_1.rBO_X_d_d);
EQ_solve_simple_1(2) = simplify(EQ_solved_unsimple_1.rBO_Y_d_d);
EQ_solve_simple_1(3) = simplify(EQ_solved_unsimple_1.rBO_Z_d_d);
EQ_solve_simple_1(4) = simplify(EQ_solved_unsimple_1.ph_d_d);
EQ_solve_simple_1(5) = simplify(EQ_solved_unsimple_1.th_d_d);
EQ_solve_simple_1(6) = simplify(EQ_solved_unsimple_1EQ.ps_d_d);
%%

alpha_simple_1 = simplify(alpha_subbed_1);
beta_simple_1 = simplify(beta_subbed_1);
PQR_simple_1 = simplify(PQR_subbed_1);
windspeed_simple_1 = simplify(windspeed_subbed_1);

ExtraEQ_simple_1 = [ ...
    alpha_simple_1      beta_simple_1    windspeed_simple_1 ...
    PQR_subbed_1 ... 
    ];

%% SUB IN THE X VALUES
% x(1) = rBO_X      x(7) = rBO_X_d     xdot(1) = x(7)       xdot(7) = EQ(1)
% x(2) = rBO_X      x(8) = rBO_Y_d     xdot(2) = x(8)       xdot(8) = EQ(2)
% x(3) = rBO_Z      x(9) = rBO_Z_d     xdot(3) = x(9)       xdot(9) = EQ(3)
% x(4) = ph         x(10) = ph_d       xdot(4) = x(10)      xdot(10) = EQ(4)
% x(5) = th         x(11) = th_d       xdot(5) = x(11)      xdot(11) = EQ(5)
% x(6) = ps         x(12) = ps_d       xdot(6) = x(12)      xdot(12) = EQ(6)



regVect = [ ...
    rBO_X rBO_Y rBO_Z ...
    rBO_X_d rBO_Y_d rBO_Z_d ...
    ph th ps ...
    ph_d th_d ps_d ...
    ];

subVect = [ ...
    str2sym('x(1)') str2sym('x(2)') str2sym('x(3)') ...
    str2sym('x(7)') str2sym('x(8)') str2sym('x(9)') ...
    str2sym('x(4)') str2sym('x(5)') str2sym('x(6)') ...
    str2sym('x(10)') str2sym('x(11)') str2sym('x(12)') ...
    ]; 

EqVect = [ ...
    str2sym('xdot(1)') str2sym('xdot(2)') str2sym('xdot(3)') ...
    str2sym('xdot(4)') str2sym('xdot(5)') str2sym('xdot(6)') ...
    str2sym('xdot(7)') str2sym('xdot(8)') str2sym('xdot(9)') ...
    str2sym('xdot(10)') str2sym('xdot(11)') str2sym('dotx(12)') ...
    ];

ExtaEqVect = [ ...
    alpha beta windspeed str2sym('p') str2sym('q') str2sym('r') ...
    ];
    

EQ_solve_simple_1 = subs(EQ_solve_simple_1,regVect,subVect);
ExtraEQ_simple_1 = subs(ExtraEQ_simple_1,regVect,subVect);

EQ_solve_final_1 = [ ...
    str2sym('x(7)') str2sym('x(8)') str2sym('x(9)') ...
    str2sym('x(10)') str2sym('x(11)') str2sym('x(12)') ...
    EQ_solve_simple_1 ...
    ];
    

EQ_string_final_1 = append(string(transpose(EqVect))," = ",string( ...
    transpose(EQ_solve_final_1)));
ExtraEQ_string_final_1 = append(string(transpose(ExtaEqVect))," = ",string( ...
    transpose(ExtraEQ_simple_1)));


    




%% WRITE THE M FILE

fileName = 'SailFunc.m';
FID = fopen(fileName,'w');

fprintf(FID,"function [t,xdot] = SailFunc(t,x)\n\n");

for i = 1:size(ExtraEQ_string_final_1,1)
    fprintf(FID,"\t%s;\n",ExtraEQ_string_final_1(i,:));
end
fprintf(FID,"\n");

fprintf(FID,"\tcurrentConfig.alpha = alpha;\n");
fprintf(FID,"\tcurrentConfig.beta = beta;\n");
fprintf(FID,"\tcurrentCongif.de = de;\n");
fprintf(FID,"\tcurrentConfig.windspeed = windspeed;\n");
fprintf(FID,"\tcurrentConfig.p = p;\n");
fprintf(FID,"\tcurrentConfig.q = q;\n");
fprintf(FID,"\tcurrentConfig.r = r;\n\n");

fprintf(FID,"\t[findAeroFlag] = checkForAeroLimits(currentConfig,aeroTriggersLast);\n\n");

fprintf(FID,"\tif findAeroFlag\n");
fprintf(FID,"\t\t[successFindAero ,aeroTriggers] = findAeroConfig( ...\n");
fprintf(FID,"\t\t\tsettings,currentConfig);\n");
fprintf(FID,"\t\tif successFindAero\n");
fprintf(FID,"\t\t\taeroTriggersLast = aeroTriggers;\n");
fprintf(FID,"\t\tend\n");
fprintf(FID,"\tend\n\n");

for i = 1:size(EQ_string_final_1,1)
    fprintf(FID,"\t%s;\n",EQ_string_final_1(i,:));
end

fprintf(FID,"\n");

fprintf(FID,"\txdot=xdot';\n\n");

fprintf(FID,"end\n\n\n");

